// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqbhbarhosxfuivuksvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xYmhiYXJob3N4ZnVpdnVrc3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxNTM5NzcsImV4cCI6MjA4NTcyOTk3N30.ZrxK0NLMqZwmbpUnH8BpcUEFjJZ2tepDTRzuzauBJH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});